<?php 

include_once drupal_get_path('module' , 'product') . '/product.entity.inc';

/**
 * Implments hook_menu
 */
function product_menu(){
	$items['product'] = array(
		'title' => '产品中心',
		'page callback' => 'product_page',
		'menu-name' => 'main-menu',
		'type' => MENU_SUGGESTED_ITEM,
		'access callback' => TRUE,
	);

	$items['product/term/%'] = array(
    'title' => '系列产品信息',
    'page callback' => 'product_term_page',
    'page arguments'=> array(2) ,
    'menu-name' => 'main-menu',
    'type' => MENU_SUGGESTED_ITEM,
   	'access callback' => TRUE,
  );

  $items['product/%'] = array(
    'title' => '产品信息',
    'page callback' => 'product_info_page',
     'page arguments'=> array(1) ,
    'menu-name' => 'main-menu',
    'type' => MENU_SUGGESTED_ITEM,
   	'access callback' => TRUE,
  );
  return $items;
}

function product_page(){
	$repo = new ProductTermRepository();
	$list = $repo-> get_top_terms();	
	$product_renders = array();
	if( $list ) {
		foreach ($list as $term ) {
			$entity = new Term( $term->tid );
			$children = $repo-> get_children($term->tid);
			$nav_image = $entity-> get_field('field_term_nav_image');

			$terms = array();
			foreach ($children as $prod_term) {
				$pro_entity = new Term( $prod_term->tid );
				$image = $pro_entity-> get_field('field_term_images');
				$pro_term =  $prod_term;
				$pro_term-> images = array(
					'#theme' => 'image' ,
					'#path'  =>  $image['uri'] ,
				);
				$pro_term->url = url('product/term/' . $prod_term-> tid);
				$terms[] = $pro_term;
			}
			$params = array(
				'terms' => $terms ,
				'top' => array( 
					'#theme' => 'image' ,
					'#path'  =>  $nav_image['uri'] ,
				) ,
				'style' => $entity-> get_field('field_term_style') ,
			);

			$params['nav'] = product_get_nav_element( $term->tid );
			$product_renders[] = common_module_template_file('product' , 'front-info' , $params);
		}	
	}
	return $product_renders;
}


function product_get_nav_element($tid){
		$repo = new ProductTermRepository();
		$entity = new Term( $tid );
		$children = $repo-> get_children($tid);
		$left = $entity-> get_field('field_term_left_image');

		$terms = array();
		foreach ($children as $term) {
			$pro_entity = new Term( $term->tid );
			$pro_term =  $term;
			$pro_term->url = url('product/term/' . $term-> tid);
			$terms[] = $pro_term;
		}

		$params = array(
			'terms' => $terms ,
			'left' => array( 
				'#theme' => 'image' ,
				'#path'  =>  $left['uri'] ,
			) ,
		);
		return common_module_template_file('product' , 'nav' , $params);
}

function product_term_page($tid){
	$entity = new Term( $tid );
	$repo = new ProductTermRepository();
	$parents = $repo-> get_parents($tid);
	$parents = array_merge($parents);
	$image = $entity-> get_field('field_term_images');
	$params = array( 
		'nav' => product_get_nav_element($parents[0]->tid) ,
		'image' => array(
			'#theme' => 'image' ,
			'#path'  =>  $image['uri'] ,
		),
		'title' =>  $entity->name ,
	);

	return common_module_template_file('product' , 'list' , $params);
}

function product_info_page($nid){
	return array();
}